gui:
  showFileTree: false
notARepository: 'quit'
git:
  paging:
    colorArg: always
    pager: delta --paging never
  autoFetch: false
customCommands:
  - key: 'x'
    command: '{{if .SelectedFile.Tracked}} git restore {{else}} rm -f {{end}} {{.SelectedFile.Name | quote}}'
    description: 'discard unstaged changes of selected file'
    context: files
    prompts:
      - type: 'confirm'
        title: 'Rollback Selected'
        body: 'Are you sure you want to rollback {{ .SelectedFile.Name }}?'
